%STARTUP

%% add MATPOWER paths
addpath( ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/lib', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/lib/t', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/data', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/most/lib', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/most/lib/t', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/mp-opt-model/lib', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/mp-opt-model/lib/t', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/mips/lib', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/mips/lib/t', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/mptest/lib', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/mptest/lib/t', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/maxloadlim', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/maxloadlim/tests', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/maxloadlim/examples', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/misc', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/reduction', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/sdp_pf', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/se', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/smartmarket', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/state_estimator', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/syngrid/lib', ...
    '/Users/honglizhaobob/Desktop/dl-hidimuq/test/classical_multimachine/matpower7.1/extras/syngrid/lib/t', ...
    '-end' );
